name: AdvancedGuilds
version: '${project.version}'
main: me.xxgradzix.advancedclans.AdvancedGuilds
api-version: '1.17'

softdepend:
  - Vault
depend: [FastAsyncWorldEdit]

commands:
  klan:
    description: klan

  gracz:
    description: gracz

  stworzkryjowke:
    description: dla admina
    permission: advancedclans.admin

  ekspedycja:
    description: dla admia
    permission: advancedclans.admin